version: '3.7'

services:
  postgres:
    container_name: postgres-local
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgresadm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - ./postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local
    restart: always
networks:
  local:
    external: true
