version: "3.7"
services:
  dbeaver:
    image: dbeaver/cloudbeaver:23.1.2
    container_name: cloudbeaver
    restart: always
    ports:
      - 8978:8978
    networks:
      - local
    volumes:
      - ./dbeaver_data:/opt/cloudbeaver/workspace
networks:
  local:
    external: true