version: '3.7'
services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql-local
    restart: always
    ports:
      - 3306:3306
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
networks:
  local:
    external: true

    